//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SessionReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://leaguedynamics.com/", ConfigurationName="SessionReference.sessionSoap")]
    public interface sessionSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://leaguedynamics.com/CheckAdminSession", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(League))]
        System.Threading.Tasks.Task<SessionReference.CheckAdminSessionResponse> CheckAdminSessionAsync(SessionReference.CheckAdminSessionRequest req);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://leaguedynamics.com/")]
    public partial class CheckAdminSessionRequest
    {
        
        private string clientTokenField;
        
        private string sessionGuidField;
        
        private string transactionRefField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string clientToken
        {
            get
            {
                return this.clientTokenField;
            }
            set
            {
                this.clientTokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string sessionGuid
        {
            get
            {
                return this.sessionGuidField;
            }
            set
            {
                this.sessionGuidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string transactionRef
        {
            get
            {
                return this.transactionRefField;
            }
            set
            {
                this.transactionRefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://leaguedynamics.com/")]
    public partial class SiteFooter
    {
        
        private LinkItem[] linksField;
        
        private string copyrightField;
        
        private Logo footerLogoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public LinkItem[] Links
        {
            get
            {
                return this.linksField;
            }
            set
            {
                this.linksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Copyright
        {
            get
            {
                return this.copyrightField;
            }
            set
            {
                this.copyrightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Logo FooterLogo
        {
            get
            {
                return this.footerLogoField;
            }
            set
            {
                this.footerLogoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://leaguedynamics.com/")]
    public partial class LinkItem
    {
        
        private string linkTextField;
        
        private string linkURLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string LinkText
        {
            get
            {
                return this.linkTextField;
            }
            set
            {
                this.linkTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string LinkURL
        {
            get
            {
                return this.linkURLField;
            }
            set
            {
                this.linkURLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://leaguedynamics.com/")]
    public partial class Logo
    {
        
        private string imageURLField;
        
        private string linkURLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ImageURL
        {
            get
            {
                return this.imageURLField;
            }
            set
            {
                this.imageURLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string LinkURL
        {
            get
            {
                return this.linkURLField;
            }
            set
            {
                this.linkURLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://leaguedynamics.com/")]
    public partial class MenuItem
    {
        
        private string menuTextField;
        
        private bool isEnabledField;
        
        private bool isExpandableField;
        
        private string linkURLField;
        
        private MenuItem[] subItemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MenuText
        {
            get
            {
                return this.menuTextField;
            }
            set
            {
                this.menuTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool IsEnabled
        {
            get
            {
                return this.isEnabledField;
            }
            set
            {
                this.isEnabledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool IsExpandable
        {
            get
            {
                return this.isExpandableField;
            }
            set
            {
                this.isExpandableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string LinkURL
        {
            get
            {
                return this.linkURLField;
            }
            set
            {
                this.linkURLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        public MenuItem[] SubItems
        {
            get
            {
                return this.subItemsField;
            }
            set
            {
                this.subItemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://leaguedynamics.com/")]
    public partial class SiteHeader
    {
        
        private Logo primaryLogoField;
        
        private Logo secondaryLogoField;
        
        private LinkItem[] linksField;
        
        private MenuItem[] menuField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Logo PrimaryLogo
        {
            get
            {
                return this.primaryLogoField;
            }
            set
            {
                this.primaryLogoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Logo SecondaryLogo
        {
            get
            {
                return this.secondaryLogoField;
            }
            set
            {
                this.secondaryLogoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public LinkItem[] Links
        {
            get
            {
                return this.linksField;
            }
            set
            {
                this.linksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public MenuItem[] Menu
        {
            get
            {
                return this.menuField;
            }
            set
            {
                this.menuField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://leaguedynamics.com/")]
    public partial class SiteChrome
    {
        
        private SiteHeader headerField;
        
        private SiteFooter footerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SiteHeader Header
        {
            get
            {
                return this.headerField;
            }
            set
            {
                this.headerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public SiteFooter Footer
        {
            get
            {
                return this.footerField;
            }
            set
            {
                this.footerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://leaguedynamics.com/")]
    public partial class Club
    {
        
        private string recordKeyField;
        
        private string orgKeyField;
        
        private string districtKeyField;
        
        private string leagueKeyField;
        
        private string nameField;
        
        private string shortNameField;
        
        private long sIDField;
        
        private string codeField;
        
        private string alternateIDField;
        
        private Address[] addressField;
        
        private Email[] emailField;
        
        private Phone[] phoneField;
        
        private Tag[] systemTagsField;
        
        private enuLeagueStatus statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RecordKey
        {
            get
            {
                return this.recordKeyField;
            }
            set
            {
                this.recordKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string OrgKey
        {
            get
            {
                return this.orgKeyField;
            }
            set
            {
                this.orgKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DistrictKey
        {
            get
            {
                return this.districtKeyField;
            }
            set
            {
                this.districtKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string LeagueKey
        {
            get
            {
                return this.leagueKeyField;
            }
            set
            {
                this.leagueKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ShortName
        {
            get
            {
                return this.shortNameField;
            }
            set
            {
                this.shortNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public long SID
        {
            get
            {
                return this.sIDField;
            }
            set
            {
                this.sIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string AlternateID
        {
            get
            {
                return this.alternateIDField;
            }
            set
            {
                this.alternateIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=9)]
        public Address[] Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=10)]
        public Email[] Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=11)]
        public Phone[] Phone
        {
            get
            {
                return this.phoneField;
            }
            set
            {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=12)]
        public Tag[] SystemTags
        {
            get
            {
                return this.systemTagsField;
            }
            set
            {
                this.systemTagsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public enuLeagueStatus Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://leaguedynamics.com/")]
    public partial class Address
    {
        
        private string addressKeyField;
        
        private string addressTypeCodeField;
        
        private string address1Field;
        
        private string address2Field;
        
        private string cityField;
        
        private string stateCodeField;
        
        private string postalCodeField;
        
        private string countryCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AddressKey
        {
            get
            {
                return this.addressKeyField;
            }
            set
            {
                this.addressKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string AddressTypeCode
        {
            get
            {
                return this.addressTypeCodeField;
            }
            set
            {
                this.addressTypeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Address1
        {
            get
            {
                return this.address1Field;
            }
            set
            {
                this.address1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Address2
        {
            get
            {
                return this.address2Field;
            }
            set
            {
                this.address2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string StateCode
        {
            get
            {
                return this.stateCodeField;
            }
            set
            {
                this.stateCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string PostalCode
        {
            get
            {
                return this.postalCodeField;
            }
            set
            {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string CountryCode
        {
            get
            {
                return this.countryCodeField;
            }
            set
            {
                this.countryCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://leaguedynamics.com/")]
    public partial class Email
    {
        
        private string emailTypeField;
        
        private string emailAddressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string EmailType
        {
            get
            {
                return this.emailTypeField;
            }
            set
            {
                this.emailTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string EmailAddress
        {
            get
            {
                return this.emailAddressField;
            }
            set
            {
                this.emailAddressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://leaguedynamics.com/")]
    public partial class Phone
    {
        
        private string phoneTypeField;
        
        private string phoneNumberField;
        
        private string extField;
        
        private bool isPreferredField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string PhoneType
        {
            get
            {
                return this.phoneTypeField;
            }
            set
            {
                this.phoneTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PhoneNumber
        {
            get
            {
                return this.phoneNumberField;
            }
            set
            {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Ext
        {
            get
            {
                return this.extField;
            }
            set
            {
                this.extField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool IsPreferred
        {
            get
            {
                return this.isPreferredField;
            }
            set
            {
                this.isPreferredField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://leaguedynamics.com/")]
    public partial class Tag
    {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://leaguedynamics.com/")]
    public enum enuLeagueStatus
    {
        
        /// <remarks/>
        Active,
        
        /// <remarks/>
        Pending,
        
        /// <remarks/>
        Deactivated,
        
        /// <remarks/>
        Applied,
        
        /// <remarks/>
        Other,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LeagueWithClubs))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://leaguedynamics.com/")]
    public partial class League
    {
        
        private string recordKeyField;
        
        private long sIDField;
        
        private string orgKeyField;
        
        private string districtKeyField;
        
        private string nameField;
        
        private string shortNameField;
        
        private enuLeagueStatus statusField;
        
        private Address[] addressField;
        
        private Email[] emailField;
        
        private Phone[] phoneField;
        
        private string codeField;
        
        private string alternateIDField;
        
        private Tag[] systemTagsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RecordKey
        {
            get
            {
                return this.recordKeyField;
            }
            set
            {
                this.recordKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long SID
        {
            get
            {
                return this.sIDField;
            }
            set
            {
                this.sIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string OrgKey
        {
            get
            {
                return this.orgKeyField;
            }
            set
            {
                this.orgKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DistrictKey
        {
            get
            {
                return this.districtKeyField;
            }
            set
            {
                this.districtKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ShortName
        {
            get
            {
                return this.shortNameField;
            }
            set
            {
                this.shortNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public enuLeagueStatus Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=7)]
        public Address[] Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=8)]
        public Email[] Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=9)]
        public Phone[] Phone
        {
            get
            {
                return this.phoneField;
            }
            set
            {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string AlternateID
        {
            get
            {
                return this.alternateIDField;
            }
            set
            {
                this.alternateIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=12)]
        public Tag[] SystemTags
        {
            get
            {
                return this.systemTagsField;
            }
            set
            {
                this.systemTagsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://leaguedynamics.com/")]
    public partial class LeagueWithClubs : League
    {
        
        private Club[] clubsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public Club[] Clubs
        {
            get
            {
                return this.clubsField;
            }
            set
            {
                this.clubsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://leaguedynamics.com/")]
    public partial class District
    {
        
        private string recordKeyField;
        
        private string orgKeyField;
        
        private string nameField;
        
        private string shortNameField;
        
        private long sIDField;
        
        private string codeField;
        
        private string alternateIDField;
        
        private Tag[] systemTagsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RecordKey
        {
            get
            {
                return this.recordKeyField;
            }
            set
            {
                this.recordKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string OrgKey
        {
            get
            {
                return this.orgKeyField;
            }
            set
            {
                this.orgKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ShortName
        {
            get
            {
                return this.shortNameField;
            }
            set
            {
                this.shortNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public long SID
        {
            get
            {
                return this.sIDField;
            }
            set
            {
                this.sIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string AlternateID
        {
            get
            {
                return this.alternateIDField;
            }
            set
            {
                this.alternateIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=7)]
        public Tag[] SystemTags
        {
            get
            {
                return this.systemTagsField;
            }
            set
            {
                this.systemTagsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://leaguedynamics.com/")]
    public partial class Organization
    {
        
        private string recordKeyField;
        
        private string nameField;
        
        private string shortNameField;
        
        private string organizationLabelField;
        
        private string districtLabelField;
        
        private string leagueLabelField;
        
        private string clubLabelField;
        
        private long sIDField;
        
        private string alternateIDField;
        
        private int adultAdminAgeLimitField;
        
        private Tag[] systemTagsField;
        
        private string logoURLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RecordKey
        {
            get
            {
                return this.recordKeyField;
            }
            set
            {
                this.recordKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ShortName
        {
            get
            {
                return this.shortNameField;
            }
            set
            {
                this.shortNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string OrganizationLabel
        {
            get
            {
                return this.organizationLabelField;
            }
            set
            {
                this.organizationLabelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string DistrictLabel
        {
            get
            {
                return this.districtLabelField;
            }
            set
            {
                this.districtLabelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string LeagueLabel
        {
            get
            {
                return this.leagueLabelField;
            }
            set
            {
                this.leagueLabelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ClubLabel
        {
            get
            {
                return this.clubLabelField;
            }
            set
            {
                this.clubLabelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public long SID
        {
            get
            {
                return this.sIDField;
            }
            set
            {
                this.sIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string AlternateID
        {
            get
            {
                return this.alternateIDField;
            }
            set
            {
                this.alternateIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int AdultAdminAgeLimit
        {
            get
            {
                return this.adultAdminAgeLimitField;
            }
            set
            {
                this.adultAdminAgeLimitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=10)]
        public Tag[] SystemTags
        {
            get
            {
                return this.systemTagsField;
            }
            set
            {
                this.systemTagsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string LogoURL
        {
            get
            {
                return this.logoURLField;
            }
            set
            {
                this.logoURLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://leaguedynamics.com/")]
    public partial class FamilyMember
    {
        
        private string recordKeyField;
        
        private string iDNUMField;
        
        private int familyIDField;
        
        private string titleField;
        
        private string prefixField;
        
        private string firstNameField;
        
        private string middleInitialField;
        
        private string lastNameField;
        
        private string suffixField;
        
        private string aliasField;
        
        private string uRLField;
        
        private string userNameField;
        
        private int birthMonthField;
        
        private int birthDayField;
        
        private int birthYearField;
        
        private System.DateTime dOBField;
        
        private enuGenders genderField;
        
        private bool isLockedField;
        
        private enuFamilyRoles familyRoleField;
        
        private Address[] addressField;
        
        private Email[] emailField;
        
        private Phone[] phoneField;
        
        private string photoURLField;
        
        private string genderCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RecordKey
        {
            get
            {
                return this.recordKeyField;
            }
            set
            {
                this.recordKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string IDNUM
        {
            get
            {
                return this.iDNUMField;
            }
            set
            {
                this.iDNUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int FamilyID
        {
            get
            {
                return this.familyIDField;
            }
            set
            {
                this.familyIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Prefix
        {
            get
            {
                return this.prefixField;
            }
            set
            {
                this.prefixField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string FirstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string MiddleInitial
        {
            get
            {
                return this.middleInitialField;
            }
            set
            {
                this.middleInitialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string LastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Suffix
        {
            get
            {
                return this.suffixField;
            }
            set
            {
                this.suffixField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Alias
        {
            get
            {
                return this.aliasField;
            }
            set
            {
                this.aliasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string URL
        {
            get
            {
                return this.uRLField;
            }
            set
            {
                this.uRLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string UserName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int BirthMonth
        {
            get
            {
                return this.birthMonthField;
            }
            set
            {
                this.birthMonthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int BirthDay
        {
            get
            {
                return this.birthDayField;
            }
            set
            {
                this.birthDayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public int BirthYear
        {
            get
            {
                return this.birthYearField;
            }
            set
            {
                this.birthYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public System.DateTime DOB
        {
            get
            {
                return this.dOBField;
            }
            set
            {
                this.dOBField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public enuGenders Gender
        {
            get
            {
                return this.genderField;
            }
            set
            {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public bool IsLocked
        {
            get
            {
                return this.isLockedField;
            }
            set
            {
                this.isLockedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public enuFamilyRoles FamilyRole
        {
            get
            {
                return this.familyRoleField;
            }
            set
            {
                this.familyRoleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=19)]
        public Address[] Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=20)]
        public Email[] Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=21)]
        public Phone[] Phone
        {
            get
            {
                return this.phoneField;
            }
            set
            {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string PhotoURL
        {
            get
            {
                return this.photoURLField;
            }
            set
            {
                this.photoURLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string GenderCode
        {
            get
            {
                return this.genderCodeField;
            }
            set
            {
                this.genderCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://leaguedynamics.com/")]
    public enum enuGenders
    {
        
        /// <remarks/>
        Male,
        
        /// <remarks/>
        Female,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://leaguedynamics.com/")]
    public enum enuFamilyRoles
    {
        
        /// <remarks/>
        Aunt,
        
        /// <remarks/>
        Father,
        
        /// <remarks/>
        Guardian,
        
        /// <remarks/>
        GrandFather,
        
        /// <remarks/>
        GrandMother,
        
        /// <remarks/>
        Mother,
        
        /// <remarks/>
        Player,
        
        /// <remarks/>
        StepFather,
        
        /// <remarks/>
        StepMother,
        
        /// <remarks/>
        Uncle,
        
        /// <remarks/>
        Other,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://leaguedynamics.com/")]
    public partial class CheckAdminSessionResponse
    {
        
        private string transactionRefField;
        
        private enuResultCodes resultCodeField;
        
        private string resultExtendedErrorField;
        
        private FamilyMember loggedInAdminField;
        
        private Organization authorizedOrganizationField;
        
        private District authorizedDistrictField;
        
        private LeagueWithClubs[] authorizedLeaguesField;
        
        private SiteChrome siteChromeField;
        
        private enuSessionPermissions[] sessionPermissionsField;
        
        private string orgKeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string transactionRef
        {
            get
            {
                return this.transactionRefField;
            }
            set
            {
                this.transactionRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public enuResultCodes resultCode
        {
            get
            {
                return this.resultCodeField;
            }
            set
            {
                this.resultCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string resultExtendedError
        {
            get
            {
                return this.resultExtendedErrorField;
            }
            set
            {
                this.resultExtendedErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public FamilyMember loggedInAdmin
        {
            get
            {
                return this.loggedInAdminField;
            }
            set
            {
                this.loggedInAdminField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public Organization authorizedOrganization
        {
            get
            {
                return this.authorizedOrganizationField;
            }
            set
            {
                this.authorizedOrganizationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public District authorizedDistrict
        {
            get
            {
                return this.authorizedDistrictField;
            }
            set
            {
                this.authorizedDistrictField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        public LeagueWithClubs[] authorizedLeagues
        {
            get
            {
                return this.authorizedLeaguesField;
            }
            set
            {
                this.authorizedLeaguesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public SiteChrome siteChrome
        {
            get
            {
                return this.siteChromeField;
            }
            set
            {
                this.siteChromeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=8)]
        public enuSessionPermissions[] sessionPermissions
        {
            get
            {
                return this.sessionPermissionsField;
            }
            set
            {
                this.sessionPermissionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string orgKey
        {
            get
            {
                return this.orgKeyField;
            }
            set
            {
                this.orgKeyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://leaguedynamics.com/")]
    public enum enuResultCodes
    {
        
        /// <remarks/>
        GeneralError,
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        InvalidClientID,
        
        /// <remarks/>
        InactiveClientID,
        
        /// <remarks/>
        InvalidClientToken,
        
        /// <remarks/>
        InvalidLeagueID,
        
        /// <remarks/>
        UnauthorizedLeagueAccess,
        
        /// <remarks/>
        UnauthorizedMethodAccess,
        
        /// <remarks/>
        InvalidLeagueStatus,
        
        /// <remarks/>
        ExceededClientQuota,
        
        /// <remarks/>
        BadCallParameter,
        
        /// <remarks/>
        DatabaseError,
        
        /// <remarks/>
        NoSeasons,
        
        /// <remarks/>
        SeasonNotFound,
        
        /// <remarks/>
        NoPlayTypes,
        
        /// <remarks/>
        NoAgeGroups,
        
        /// <remarks/>
        NoPlayLevels,
        
        /// <remarks/>
        PlayLevelNotFound,
        
        /// <remarks/>
        AgeGroupNotFound,
        
        /// <remarks/>
        NoRiskStatuses,
        
        /// <remarks/>
        NoLicenseLevels,
        
        /// <remarks/>
        NoOfficerRoles,
        
        /// <remarks/>
        OrganizationNotFound,
        
        /// <remarks/>
        DistrictNotFound,
        
        /// <remarks/>
        LeagueNotFound,
        
        /// <remarks/>
        NoClubs,
        
        /// <remarks/>
        ClubNotFound,
        
        /// <remarks/>
        PlayerNotFound,
        
        /// <remarks/>
        NoMatchingPlayers,
        
        /// <remarks/>
        FamilyNotFound,
        
        /// <remarks/>
        NoMatchingFamilies,
        
        /// <remarks/>
        FamilyMemberNotFound,
        
        /// <remarks/>
        NoMatchingFamilyMembers,
        
        /// <remarks/>
        AdminNotFound,
        
        /// <remarks/>
        NoMatchingAdmins,
        
        /// <remarks/>
        NoMatchingOfficers,
        
        /// <remarks/>
        TeamNotFound,
        
        /// <remarks/>
        NoMatchingTeams,
        
        /// <remarks/>
        TournamentNotFound,
        
        /// <remarks/>
        NoMatchingTournaments,
        
        /// <remarks/>
        GameNotFound,
        
        /// <remarks/>
        NoMatchingGames,
        
        /// <remarks/>
        NoMatchingStandings,
        
        /// <remarks/>
        VenueNotFound,
        
        /// <remarks/>
        NoMatchingVenues,
        
        /// <remarks/>
        RequiredParameterMissing,
        
        /// <remarks/>
        InvalidEmailFormat,
        
        /// <remarks/>
        InvalidPhoneFormat,
        
        /// <remarks/>
        InvalidPostalCodeFormat,
        
        /// <remarks/>
        ApplicationAlreadyExists,
        
        /// <remarks/>
        NoApplicationExists,
        
        /// <remarks/>
        ApplicationStatusInvalid,
        
        /// <remarks/>
        AlreadyOnTeam,
        
        /// <remarks/>
        MemberAddedPostActivation,
        
        /// <remarks/>
        MultipleApplicationsNotAllowed,
        
        /// <remarks/>
        MultiRosteringNotAllowed,
        
        /// <remarks/>
        InvalidTagCategory,
        
        /// <remarks/>
        InvalidTag,
        
        /// <remarks/>
        InvalidTagValue,
        
        /// <remarks/>
        InvalidSession,
        
        /// <remarks/>
        InvalidELAKey,
        
        /// <remarks/>
        InvalidExtraFieldKey,
        
        /// <remarks/>
        InvalidExtraFieldValue,
        
        /// <remarks/>
        RequiredExtraFieldMissing,
        
        /// <remarks/>
        FailedToUpdateOneOrMoreExtraFields,
        
        /// <remarks/>
        RegistrationDisabled,
        
        /// <remarks/>
        TeamFormationDisabled,
        
        /// <remarks/>
        PhotoLocked,
        
        /// <remarks/>
        BirthCertificateLocked,
        
        /// <remarks/>
        CertificateLocked,
        
        /// <remarks/>
        BackgroundCheckDisabled,
        
        /// <remarks/>
        RiskStatusLocked,
        
        /// <remarks/>
        NoAdminRoles,
        
        /// <remarks/>
        InvalidAdminRole,
        
        /// <remarks/>
        InvalidLicenseLevel,
        
        /// <remarks/>
        InvalidMailingKey,
        
        /// <remarks/>
        RefPoolNotFound,
        
        /// <remarks/>
        NoInfractionTypes,
        
        /// <remarks/>
        InvalidIfractionKey,
        
        /// <remarks/>
        RefereeScheduleConflict,
        
        /// <remarks/>
        ScoreActionNotAllowedAtThisTime,
        
        /// <remarks/>
        OperationTimeout,
        
        /// <remarks/>
        ExceededCapacity,
        
        /// <remarks/>
        InvalidMailingStatus,
        
        /// <remarks/>
        InvalidFeeKey,
        
        /// <remarks/>
        NoGenders,
        
        /// <remarks/>
        InvalidGenderCode,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://leaguedynamics.com/")]
    public enum enuSessionPermissions
    {
        
        /// <remarks/>
        UploadPortalAccess,
        
        /// <remarks/>
        UploadPortalRiskStatus,
        
        /// <remarks/>
        UploadPortalCoachCertification,
        
        /// <remarks/>
        UploadPortalSkipReview,
        
        /// <remarks/>
        UploadPortalReviewAccess,
        
        /// <remarks/>
        UploadPortalPlayerUpload,
        
        /// <remarks/>
        UploadPortalAdminUpload,
        
        /// <remarks/>
        MessagingPortalAccess,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface sessionSoapChannel : SessionReference.sessionSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class sessionSoapClient : System.ServiceModel.ClientBase<SessionReference.sessionSoap>, SessionReference.sessionSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public sessionSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(sessionSoapClient.GetBindingForEndpoint(endpointConfiguration), sessionSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public sessionSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(sessionSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public sessionSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(sessionSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public sessionSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<SessionReference.CheckAdminSessionResponse> CheckAdminSessionAsync(SessionReference.CheckAdminSessionRequest req)
        {
            return base.Channel.CheckAdminSessionAsync(req);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.sessionSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.sessionSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.sessionSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://ldstage.sportsaffinity.com/api/endpoints/v4/session.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.sessionSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://ldstage.sportsaffinity.com/api/endpoints/v4/session.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            sessionSoap,
            
            sessionSoap12,
        }
    }
}
