# This file is a template, and might need editing before it works on your project.
# The following script will work for any project that can be built from command line by msbuild
# It uses powershell shell executor, so you need to add the following line to your config.toml file
# (located in gitlab-runner.exe directory):
#   shell = "powershell"
#
# The script is composed of 3 stages: build, test and deploy.
#
# The build stage restores NuGet packages and uses msbuild to build the exe and msi
# One major issue you'll find is that you can't build msi projects from command line
# if you use vdproj.  There are workarounds building msi via devenv, but they rarely work
# The best solution is migrating your vdproj projects to WiX, as it can be build directly
# by msbuild.
#
# The test stage runs nunit from command line against Test project inside your solution
# It also saves the resulting TestResult.xml file
#
# The deploy stage copies the exe and msi from build stage to a network drive
# You need to have the network drive mapped as Local System user for gitlab-runner service to see it
# The best way to persist the mapping is via a scheduled task (see: https://stackoverflow.com/a/7867064/1288473),
# running the following batch command: net use P: \\x.x.x.x\Projects /u:your_user your_pass /persistent:yes


# place project specific paths in variables to make the rest of the script more generic
variables:
  GITLAB_REGISTRY_TOKEN: 'M6Dwxz7k6qALSijVfnM7'

# IMPORTANT!!! Use "git config --system core.longpaths true" command on Windows server

stages:
  - build
  - test
  - docker

backend:
  stage: build
  only:
    - master
    - develop
    - merge_requests
  script:
    - 'git clean -ffdx'
    - 'dotnet restore ./WeSafe.Web/WeSafe.Web.csproj'
    - 'dotnet build --no-restore ./WeSafe.Web/WeSafe.Web.csproj'
    - 'git clean -ffdx'
  tags:
    - dotnetcore

backend-test:
  stage: test
  only:
    - master
    - develop
    - merge_requests
  script:
    - 'git clean -ffdx'
    - 'dotnet test WeSafe.NET.sln'
    - 'git clean -ffdx'
  tags:
    - dotnetcore

frontend:
  stage: build
  only:
    - master
    - develop
    - merge_requests
  script:
    - 'cd ./WeSafe.Web/ClientApp'
    - 'npm install'
    - 'npm run build:prod'
    - 'git clean -ffdx'
  tags:
    - dotnetcore

telegram-bot:
  stage: build
  only:
    - master
    - develop
    - merge_requests
  script:
    - 'dotnet restore ./WeSafe.TelegramBot.Console/WeSafe.TelegramBot.NetCore.csproj'
    - 'dotnet build --no-restore ./WeSafe.TelegramBot.Console/WeSafe.TelegramBot.NetCore.csproj'
    - 'git clean -ffdx'
  tags:
    - dotnetcore

monitoring:
  stage: build
  only:
    - master
    - develop
    - merge_requests
  script:
    - 'dotnet restore ./WeSafe.Monitoring.Console/WeSafe.Monitoring.Console.csproj'
    - 'dotnet build --no-restore ./WeSafe.Monitoring.Console/WeSafe.Monitoring.Console.csproj'
    - 'git clean -ffdx'
  tags:
    - dotnetcore

nano:
  stage: build
  only:
    - master
    - develop
    - merge_requests
  script:
    - 'dotnet restore ./WeSafe.WebApi.Light/WeSafe.Nano.WebApi.csproj'
    - 'dotnet build --no-restore ./WeSafe.WebApi.Light/WeSafe.Nano.WebApi.csproj'
    - 'git clean -ffdx'
  tags:
    - dotnetcore

build-image:
  stage: docker
  only:
    - master
  script:
    - 'docker build -t registry.gitlab.com/xeltan/wesafe.net .'
    - 'docker build -t registry.gitlab.com/xeltan/wesafe.net/bot -f WeSafe.TelegramBot.Console/Dockerfile .'
    - 'docker build -t registry.gitlab.com/xeltan/wesafe.net/monitoring -f WeSafe.Monitoring.Console/Dockerfile .'
    - 'docker build -t registry.gitlab.com/xeltan/wesafe.net/nano -f WeSafe.WebApi.Light/Dockerfile .'
    - 'docker login -u xeltan -p $GITLAB_REGISTRY_TOKEN registry.gitlab.com'
    - 'docker push registry.gitlab.com/xeltan/wesafe.net'
    - 'docker push registry.gitlab.com/xeltan/wesafe.net/bot'
    - 'docker push registry.gitlab.com/xeltan/wesafe.net/monitoring'
    - 'docker push registry.gitlab.com/xeltan/wesafe.net/nano'
    - 'git clean -ffdx'
  tags:
    - dotnetcore

build-dev-image:
  stage: docker
  only:
    - develop
  script:
    - 'docker build -t registry.gitlab.com/xeltan/wesafe.net:dev .'
    - 'docker build -t registry.gitlab.com/xeltan/wesafe.net/bot:dev -f WeSafe.TelegramBot.Console/Dockerfile .'
    - 'docker build -t registry.gitlab.com/xeltan/wesafe.net/monitoring:dev -f WeSafe.Monitoring.Console/Dockerfile .'
    - 'docker build -t registry.gitlab.com/xeltan/wesafe.net/nano:dev -f WeSafe.WebApi.Light/Dockerfile .'
    - 'docker login -u xeltan -p $GITLAB_REGISTRY_TOKEN registry.gitlab.com'
    - 'docker push registry.gitlab.com/xeltan/wesafe.net:dev'
    - 'docker push registry.gitlab.com/xeltan/wesafe.net/bot:dev'
    - 'docker push registry.gitlab.com/xeltan/wesafe.net/monitoring:dev'
    - 'docker push registry.gitlab.com/xeltan/wesafe.net/nano:dev'
    - 'git clean -ffdx'
  tags:
    - dotnetcore
